[book]
authors = ["bounderoll"]
language = "en"
multilingual = false
src = "src"
title = "mdbook"

[preprocessor.drawio]
command = "mdbook-drawio"

[output.html]
additional-css = ["src/assets/custom.css"]
